name: 'MT论坛签到测试'

# 只允许手动触发，用于测试签到功能
on:
  workflow_dispatch:
    inputs:
      test_accounts:
        description: '测试账号(可选，默认使用环境变量)'
        required: false
        default: ''

jobs:
  test_sign_in:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 安装Python和依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        sudo pip3 install requests

    - name: 显示Python版本
      run: python3 --version

    - name: 输出调试信息
      run: |
        echo "当前工作目录: $(pwd)"
        ls -la

    - name: 测试手动输入的账号
      if: "${{ github.event.inputs.test_accounts != '' }}"
      run: |
        echo "使用手动输入的测试账号"
        python3 ./index.py "${{ github.event.inputs.test_accounts }}"

    - name: 测试环境变量中的账号
      if: "${{ github.event.inputs.test_accounts == '' }}"
      run: |
        echo "使用环境变量中的账号"
        python3 ./index.py "${{ secrets.MTUSER }}" 