name: 'MT论坛签到测试'

# 只允许手动触发，用于测试签到功能
on:
  workflow_dispatch:
    inputs:
      test_accounts:
        description: '测试账号(可选，默认使用环境变量)'
        required: false
        default: ''

jobs:
  test_sign_in:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip' # 启用pip缓存
        
    - name: 缓存Python依赖
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 显示Python版本
      run: python --version

    - name: 输出调试信息
      run: |
        echo "当前工作目录: $(pwd)"
        ls -la

    - name: 测试手动输入的账号
      if: "${{ github.event.inputs.test_accounts != '' }}"
      run: |
        echo "使用手动输入的测试账号"
        python ./index.py "${{ github.event.inputs.test_accounts }}"

    - name: 测试环境变量中的账号
      if: "${{ github.event.inputs.test_accounts == '' }}"
      run: |
        echo "使用环境变量中的账号"
        python ./index.py "${{ secrets.MTUSER }}" 